/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BaiQuanLySinhVien;

import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class BangQLSV extends javax.swing.JFrame {

    /**
     * Creates new form BangQLSV
     */
    public BangQLSV() {
        initComponents();
        LoadDataJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttdelete = new javax.swing.JButton();
        bttExit = new javax.swing.JButton();
        bttUpdate = new javax.swing.JButton();
        bttNew = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoDoThan = new javax.swing.JRadioButton();
        rdoDaKetHon = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        bttdelete.setText("Delete");
        bttdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttdeleteActionPerformed(evt);
            }
        });

        bttExit.setText("Exit");
        bttExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExitActionPerformed(evt);
            }
        });

        bttUpdate.setText("Update");
        bttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttUpdateActionPerformed(evt);
            }
        });

        bttNew.setText("New");
        bttNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNewActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã sinh viên:");

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Họ và tên:");

        jLabel5.setText("Tình trạng:");

        jLabel6.setText("Email:");

        rdoNam.setText("Nam");

        rdoNu.setText("Nữ");

        rdoDoThan.setText("Độc thân");

        rdoDaKetHon.setText("Đã kết hôn");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rdoNam)
                                                    .addComponent(rdoDoThan))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rdoDaKetHon)
                                                    .addComponent(rdoNu)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3))
                                        .addGap(16, 16, 16)))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttUpdate)
                                    .addComponent(bttdelete)
                                    .addComponent(bttNew)
                                    .addComponent(bttExit))))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttdelete))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(bttUpdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(bttNew))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu)
                    .addComponent(bttExit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdoDoThan)
                    .addComponent(rdoDaKetHon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttdeleteActionPerformed
        // TODO add your handling code here:
         try {
            Connection conn = KetNoi();
            
            Statement sttm = conn.createStatement();
            String sql = "Delete from QUANLYSINHVIEN where uname=?";
            
            PreparedStatement delete = conn.prepareStatement(sql);
            delete.setString(1, txtID.getText());
            delete.executeUpdate();
            conn.close();
            LoadDataJTable();
        } catch (Exception e) {
            System.err.println("No");
        }
    }//GEN-LAST:event_bttdeleteActionPerformed

    private void bttNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNewActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtHoTen.setText("");
        txtEmail.setText("");
        txtID.requestFocus(); //hien dau gach
    }//GEN-LAST:event_bttNewActionPerformed

    private void bttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttUpdateActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        int index = table1.getSelectedRow();
        if(txtID.getText()== (String)table1.getValueAt(index,0)) {
            sb.append("Khong có ID\n");
        } 
        
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Erro", 0);
        } else { 
        try {
                Connection conn = KetNoi();
                String sql = "Update QUANLYSINHVIEN set  HoTen=?, Email=?, GioiTinh=?, TinhTrang=? where ID=?";

                PreparedStatement update = conn.prepareStatement(sql);
                update.setString(1, txtHoTen.getText());
                update.setString(2, txtEmail.getText());
                if(rdoNam.isSelected()){
                    update.setString(3,"Nam");
                }else{
                    update.setString(3, "Nữ");
                }
                if(rdoDaKetHon.isSelected()){
                    update.setString(4, "Đã kêt hôn");
                }else{
                    update.setString(4, "Độc thân");
                }
                update.setString(5, txtID.getText());
                update.executeUpdate();
                conn.close();
                LoadDataJTable();
                
            } catch (Exception e) {
                System.err.println("No");
            }
        }
    }//GEN-LAST:event_bttUpdateActionPerformed

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
        int rows = table1.getSelectedRow();
        txtID.setText(table1.getValueAt(rows, 0).toString());
        txtHoTen.setText(table1.getValueAt(rows, 1).toString());
        txtEmail.setText(table1.getValueAt(rows, 2).toString());
        if(table1.getValueAt(rows, 3).toString() == "Nam"){
            rdoNam.isSelected();
        }else{
            rdoNu.isSelected();
        }
        if(table1.getValueAt(rows, 4).toString() == "Đã kêt hôn"){
            rdoDaKetHon.isSelected();
        }else{
            rdoDoThan.isSelected();
        }
    }//GEN-LAST:event_table1MouseClicked

    private void bttExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangQLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttExit;
    private javax.swing.JButton bttNew;
    private javax.swing.JButton bttUpdate;
    private javax.swing.JButton bttdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoDaKetHon;
    private javax.swing.JRadioButton rdoDoThan;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
    private Connection KetNoi() throws SQLException, ClassNotFoundException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=demo;";
        Connection conn = DriverManager.getConnection(url, "sa", "sa");
        return conn;
    }
    private void LoadDataJTable() {
        try {
            Connection conn = KetNoi();
            
            Statement sttm = conn.createStatement();
            String sql = "Select * from QUANLYSINHVIEN";
            ResultSet rs = sttm.executeQuery(sql);
            
            if (conn != null) {
                System.err.println("Thanh cong");
                
                Object[] columns = {"Mã SV", "Họ Tên SV", "Email", "Giới Tính","Tình Trạng"};
                DefaultTableModel model = (DefaultTableModel) table1.getModel();
                model.setColumnIdentifiers(columns);
                model.setRowCount(0);
                while (rs.next()) {
                    String ID = rs.getString("ID");
                    String Name = rs.getString("HoTen");
                    String Email = rs.getString("Email");
                    String GioiTinh = rs.getString("GioiTinh");
                    String TinhTrang = rs.getString("TinhTrang");
                    
                    model.addRow(new Object[]{ID, Name, Email, GioiTinh,TinhTrang});
                }
                
            } else {
                System.err.println("No");
            }
        } catch (Exception e) {
       
        }
        ButtonGroup GroupGT = new ButtonGroup();
        GroupGT.add(rdoNam);
        GroupGT.add(rdoNu);
        
        ButtonGroup GroupTT = new ButtonGroup();
        GroupTT.add(rdoDaKetHon);
        GroupTT.add(rdoDoThan);
            
        }
}

