/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bang;

import java.io.*;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SonHeo
 */
public class Bang1 extends javax.swing.JFrame {

    ArrayList<NhanVien> myList = new ArrayList<>();
    private int currentSelected;

    /**
     * Creates new form Bang1
     */
    public Bang1() {
        initComponents();

        ButtonGT_TT();
        LoadDataJTable(myList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoDocThan = new javax.swing.JRadioButton();
        rdoDaKetHon = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        bttDelete = new javax.swing.JButton();
        bttUpdate = new javax.swing.JButton();
        bttNew = new javax.swing.JButton();
        bttExit = new javax.swing.JButton();
        txtMaNhanVien = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        bttOpen = new javax.swing.JButton();
        bttSave = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnEnd = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblDem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setText("Ma Nhân Viên:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Email:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Tình trạng:");

        rdoNam.setText("Nam");

        rdoNu.setText("Nữ");

        rdoDocThan.setText("Độc thân");

        rdoDaKetHon.setText("Đã kết hôn");

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        bttDelete.setText("Delete");
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        bttUpdate.setText("Update");
        bttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttUpdateActionPerformed(evt);
            }
        });

        bttNew.setText("New");
        bttNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNewActionPerformed(evt);
            }
        });

        bttExit.setText("Exit");
        bttExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExitActionPerformed(evt);
            }
        });

        bttOpen.setText("Open file");
        bttOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttOpenActionPerformed(evt);
            }
        });

        bttSave.setText("Save file");
        bttSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNhanVien)
                            .addComponent(txtHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttOpen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoDocThan)
                            .addComponent(rdoNam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoNu)
                            .addComponent(rdoDaKetHon))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(bttSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttUpdate)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttExit)
                                    .addComponent(bttNew))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttOpen)))
                    .addComponent(bttDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttUpdate)
                            .addComponent(bttSave)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttNew)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bttExit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoDocThan)
                            .addComponent(rdoDaKetHon)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rdoNu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFirst.setText("<<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnEnd.setText(">>");
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });

        btnPrevious.setText("|<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText(">|");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblDem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDem.setText("1/3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblDem)
                        .addGap(29, 29, 29)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnEnd)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(lblDem))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bttExitActionPerformed

    private void bttOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttOpenActionPerformed
        JFileChooser mofile = new JFileChooser();
        int r = mofile.showOpenDialog(null);

        if (r == JFileChooser.APPROVE_OPTION) {

            try {
                String file = mofile.getSelectedFile().toString();
                FileInputStream fis = new FileInputStream(file);
                ObjectInputStream ois = new ObjectInputStream(fis);

                myList = (ArrayList<NhanVien>) ois.readObject();
                LoadDataJTable(myList);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Invalid format file");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Class not found");
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bttOpenActionPerformed

    private void bttSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSaveActionPerformed
        System.err.println(myList);
        if (myList.equals("")) {
            JOptionPane.showMessageDialog(this, "Ban trong khong the xuat", "Erro", 0);
        } else {
            JFileChooser c = new JFileChooser();
            int r = c.showSaveDialog(null);
            if (r == JFileChooser.APPROVE_OPTION) {
                try {
                    String file = c.getSelectedFile().toString();

                    FileOutputStream fos = new FileOutputStream(file);
                    ObjectOutputStream oos = new ObjectOutputStream(fos);

                    oos.writeObject(myList);
                    JOptionPane.showMessageDialog(this, "File saved");
                } catch (IOException ex) {
                    System.out.println(ex.toString());
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bttSaveActionPerformed

    private void bttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttUpdateActionPerformed
        int iSelect = table1.getSelectedRow();
        String maNV = txtMaNhanVien.getText();
        String hoten = txtHoTen.getText();
        String email = txtEmail.getText();
        String gioitinh = "";
        String tinhtrang = "";

        table1.setValueAt(maNV, iSelect, 0);
        table1.setValueAt(hoten, iSelect, 1);
        table1.setValueAt(email, iSelect, 2);
        if (rdoNam.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "Nữ";
        }
        table1.setValueAt(gioitinh, iSelect, 3);
        if (rdoDaKetHon.isSelected()) {
            tinhtrang = "Da kết hôn";
        } else {
            tinhtrang = "độc thân";
        }
        table1.setValueAt(tinhtrang, iSelect, 4);

        myList.set(iSelect, new NhanVien(maNV, hoten, email, gioitinh, tinhtrang));
        // TODO add your handling code here:
    }//GEN-LAST:event_bttUpdateActionPerformed
    public void fillDataTableToForm(int rows) {
        txtMaNhanVien.setText(table1.getValueAt(rows, 0).toString());
        txtHoTen.setText(table1.getValueAt(rows, 1).toString());
        txtEmail.setText(table1.getValueAt(rows, 2).toString());
        if (table1.getValueAt(rows, 3).toString() == "Nam") {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (table1.getValueAt(rows, 4).toString() == "Đã kêt hôn") {
            rdoDaKetHon.setSelected(true);
        } else {
            rdoDocThan.setSelected(true);
        }
    }
    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        int rows = table1.getSelectedRow();
        fillDataTableToForm(rows);
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        int iSelect = table1.getSelectedRow();
        model.removeRow(iSelect);
        myList.remove(iSelect);
        // TODO add your handling code here:
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void bttNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNewActionPerformed
        String id = txtMaNhanVien.getText();
        String name = txtHoTen.getText();
        String email = txtEmail.getText();
        String gioitinh = rdoNam.isSelected() ? "Nam" : "Nữ";
        String tinhtrang = rdoDaKetHon.isSelected() ? "Đã kết hôn" : "Độc thân";

        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.addRow(new Object[]{id, name, email, gioitinh, tinhtrang});

        myList.add(new NhanVien(id, name, email, gioitinh, tinhtrang));
        // TODO add your handling code here:
    }//GEN-LAST:event_bttNewActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        currentSelected = 0;
        table1.setRowSelectionInterval(currentSelected, 0);
        setSelectRow(currentSelected, table1);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        currentSelected--;
        if (currentSelected < 0) {
            currentSelected = 0;
        }
        table1.setRowSelectionInterval(currentSelected, 0);
        setSelectRow(currentSelected, table1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        currentSelected++;
        if (currentSelected > model.getRowCount() - 1) {
            currentSelected = model.getColumnCount() - 1;
        }
        table1.setRowSelectionInterval(currentSelected, 0);
        setSelectRow(currentSelected, table1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        currentSelected = model.getRowCount() - 1;
        table1.setRowSelectionInterval(currentSelected, 0);
        setSelectRow(currentSelected, table1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bang1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bang1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttExit;
    private javax.swing.JButton bttNew;
    private javax.swing.JButton bttOpen;
    private javax.swing.JButton bttSave;
    private javax.swing.JButton bttUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDem;
    private javax.swing.JRadioButton rdoDaKetHon;
    private javax.swing.JRadioButton rdoDocThan;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNhanVien;
    // End of variables declaration//GEN-END:variables

    private void LoadDataJTable(ArrayList<NhanVien> myList) {
        Object[] columns = {"Mã SV", "Họ Tên SV", "Email", "Giới Tính", "Tình Trạng"};
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        model.setColumnIdentifiers(columns);
        model.setRowCount(0);
        if (myList.isEmpty() || myList == null) {
            model.setRowCount(0);
        } else {
            model.setRowCount(0);
            for (NhanVien nv : myList) {
                model.addRow(new Object[]{nv.getManv(), nv.getHoten(), nv.getEmail(), nv.getGioitinh(), nv.getTinhtrang()});
            
            }
            setSelectRow(currentSelected, table1);
        }
    }

    private void ButtonGT_TT() {
        ButtonGroup GroupNam_Nu = new ButtonGroup();
        GroupNam_Nu.add(rdoNam);
        GroupNam_Nu.add(rdoNu);

        ButtonGroup GroupDocThan_CoChu = new ButtonGroup();
        GroupDocThan_CoChu.add(rdoDaKetHon);
        GroupDocThan_CoChu.add(rdoDocThan);
    }

    public void setSelectRow(int i, JTable table1) {
        if (i >= 0) {
            DefaultTableModel model = (DefaultTableModel) table1.getModel();

            table1.changeSelection(i, 0, false, false);

            changRecordStatus(i, table1);

            if (i <= model.getRowCount()) {
                fillDataTableToForm(i);
            } else {
                lblDem.setText("No record");
            }
        }
    }

    public void changRecordStatus(int i, JTable table1) {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();
        lblDem.setText(i + 1 + "/" + model.getRowCount());
    }
}
