/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BangDangNhap;

import Dao.BangDiemDao;
import Dao.LichSuDao;
import Dao.SinhVienDao;
import Helper.DataValidator;
import Helper.MessageDialogHelper;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDiem;
import model.LichSu;
import model.SinhVien;

/**
 *
 * @author Admin
 */
public class GPAManagementPanel extends javax.swing.JPanel {
    private MainForm parent;
    private DefaultTableModel tblModel;
    private BangDiemHoi bangdiemhoi;
    /**
     * Creates new form NewJPanel
     */
    public GPAManagementPanel() {
        initComponents();
        
        initTable();
        LoadDataToTable();
    }
    private void initTable(){
        Object[] columns = {"Mã Sinh Viên","JAVA","SQL","Phân Tích Hệ Thống","IOS","PHP", "Điểm Trung Bình"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columns);
        tblBangDiem.setModel(tblModel);
    }
    private void LoadDataToTable(){
        try {
            BangDiemDao dao = new BangDiemDao();
            List<BangDiem> list = dao.findAll();
            tblModel.setRowCount(0);
            for (BangDiem bd : list) {
                tblModel.addRow(new Object[]{ bd.getMaSinhVien(), bd.getJava(), bd.getSQL(),
                                bd.getPhanTichHeThong(), bd.getIos(), bd.getPhp(),
                                (bd.getJava() + bd.getSQL() + bd.getPhanTichHeThong() + bd.getIos() + bd.getPhp())/5});
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parent, e.getMessage(), "Lỗi");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        txtJava = new javax.swing.JTextField();
        txtSql = new javax.swing.JTextField();
        txtPhanTichHeThong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIOS = new javax.swing.JTextField();
        txtPHP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblGpa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangDiem = new javax.swing.JTable();
        btnTop = new javax.swing.JButton();
        btnXemTatCa = new javax.swing.JButton();
        txtStudentIDSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Điểm");

        jLabel3.setText("Mã Sinh viên:");

        jLabel4.setText("Họ và tên:");

        jLabel5.setText("JAVA:");

        txtStudentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStudentIDFocusLost(evt);
            }
        });

        jLabel6.setText("SQL:");

        jLabel7.setText("Phân tích hệ thống:");

        jLabel10.setText("PHP:");

        jLabel11.setText("IOS:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txtJava, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSql, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhanTichHeThong, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIOS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPHP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhanTichHeThong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblGpa.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        lblGpa.setForeground(new java.awt.Color(0, 0, 0));
        lblGpa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGpa.setText("0.0");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setText("Điểm Trung Bình");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNew.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\new-icon-16.png")); // NOI18N
        btnNew.setText("Nhập Mới ");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Save-icon.png")); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-edit-delete-icon-16.png")); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-document-edit-icon-16.png")); // NOI18N
        btnUpdate.setText("Cập Nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        tblBangDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangDiemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBangDiem);

        btnTop.setText("TOP");
        btnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopActionPerformed(evt);
            }
        });

        btnXemTatCa.setText("Xem Tất Cả");
        btnXemTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTop)
                        .addGap(18, 18, 18)
                        .addComponent(btnXemTatCa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnNew)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTop)
                    .addComponent(btnXemTatCa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("Mã Sinh Viên:");

        btnSearch.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\search-icon-16.png")); // NOI18N
        btnSearch.setText("Tìm  Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtStudentIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtStudentID.setText("");
        txtIOS.setText("");
        txtJava.setText("");
        txtPHP.setText("");
        txtPhanTichHeThong.setText("");
        txtName.setText("");
        txtSql.setText("");
        
        txtStudentIDSearch.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed
    private void LichSuDiem(String MaSV, String GhiChu){   
        try {
            LichSu LS = new LichSu();
            LS.setMaSV(MaSV); 
            LS.setGhiChu(GhiChu);

            LichSuDao dao = new LichSuDao();
            dao.insert_Diem(LS);

        } catch (Exception e) {
            e.printStackTrace();
            
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Mã Sinh Viên Cần Phải Nhập");
        DataValidator.validateEmpty(txtIOS, sb, "IOS Cần phải nhập điểm");
        DataValidator.validateEmpty(txtJava, sb, "JAVA Cần phải nhập điểm");
        DataValidator.validateEmpty(txtName, sb, "Cần phải nhập tên");
        DataValidator.validateEmpty(txtPHP, sb, "Cần phải nhập điểm PHP");
        DataValidator.validateEmpty(txtPhanTichHeThong, sb, "Phân Tích Hệ Thống cần phải nhập điểm");
        DataValidator.validateEmpty(txtSql, sb, "SQL Cần phải nhập điểm");
        
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parent, sb.toString(), "Lỗi");
            return;
        }
        
        try {
            
            BangDiem bd = new BangDiem();
            bd.setMaSinhVien(txtStudentID.getText());
            bd.setJava(Float.parseFloat(txtJava.getText()));
            bd.setSQL(Float.parseFloat(txtSql.getText()));
            bd.setPhanTichHeThong(Float.parseFloat(txtPhanTichHeThong.getText()));
            bd.setIos(Float.parseFloat(txtIOS.getText()));
            bd.setPhp(Float.parseFloat(txtPHP.getText()));
            
            BangDiemDao dao = new BangDiemDao();  
            if (dao.findByMaSinhVien(txtStudentID.getText()) != null) {
                if(MessageDialogHelper.showConfirmDialog(parent, "Trong Danh Sách Đã Mã Sinh Viên. \n Bạn Có Muốn Lưu Thêm?",
                        "Hỏi") == JOptionPane.NO_OPTION);
                return;
            }else{
                if (dao.insert(bd)) {
                    MessageDialogHelper.showMessageDialog(parent, "Bảng Điểm Đã Được Lưu", "Thông Báo");
                }else{
                    MessageDialogHelper.showErrorDialog(parent, "Bảng Điểm Không Lưu Được", "Thông Báo");
                }
            }
            LichSuDiem(txtStudentID.getText(), "Lưu");
            LoadDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parent, e.toString(), "Lỗi");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtStudentIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStudentIDFocusLost
        try {
            SinhVienDao dao = new SinhVienDao();
            SinhVien sv = dao.findByID(txtStudentID.getText());
            if (sv != null) {
                txtName.setText(sv.getHoTen());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtIOS.getText().equals("") || txtJava.getText().equals("") || txtPHP.getText().equals("")
                || txtPhanTichHeThong.getText().equals("")|| txtSql.getText().equals("")) {
            return;
        }
        float ios = Float.parseFloat(txtIOS.getText());
        float java = Float.parseFloat(txtJava.getText());
        float php = Float.parseFloat(txtPHP.getText());
        float PhanTichHeThong = Float.parseFloat(txtPhanTichHeThong.getText());
        float sql = Float.parseFloat(txtSql.getText());
        
        float avg = (ios + java + php + PhanTichHeThong + sql) / 5 ;
        
        String st = String.format("%.2f", avg);
        lblGpa.setText(st);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       
        try {
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findByMaSinhVien(txtStudentIDSearch.getText());
            
            if (bd != null) {
                txtStudentID.setText(bd.getMaSinhVien());
                txtJava.setText(String.format("%.2f", bd.getJava()));
                txtIOS.setText(String.format("%.2f", bd.getIos()));
                txtPHP.setText(String.format("%.2f", bd.getPhp()));
                txtPhanTichHeThong.setText(String.format("%.2f", bd.getPhanTichHeThong()));
                txtSql.setText(String.format("%.2f", bd.getSQL()));
                
                txtStudentIDFocusLost(null);
            }else{
                MessageDialogHelper.showMessageDialog(parent, "Không Tìm Thấy Mã Sinh Viên Trong Danh Sách", "Thông Báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parent, e.toString(), "Lỗi");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Mã Sinh Viên Trống Hoặc Sai Mã Sinh Viên ");
        if (sb.length() >0) {
            MessageDialogHelper.showErrorDialog(parent, sb.toString(), "Lỗi");
        }
        
        if (MessageDialogHelper.showConfirmDialog(parent, "Bạn muốn cập nhập sinh viên không",
                "Hỏi") == JOptionPane.NO_OPTION ) {
            return;          
        }
        try {
            
            BangDiem bd = new BangDiem();
            bd.setMaSinhVien(txtStudentID.getText());
            bd.setJava(Float.parseFloat(txtJava.getText()));
            bd.setSQL(Float.parseFloat(txtSql.getText()));
            bd.setPhanTichHeThong(Float.parseFloat(txtPhanTichHeThong.getText()));
            bd.setIos(Float.parseFloat(txtIOS.getText()));
            bd.setPhp(Float.parseFloat(txtPHP.getText()));
            
            BangDiemDao dao = new BangDiemDao();
            if (dao.findByMaSinhVien(txtStudentID.getText()) != null) {
                if(MessageDialogHelper.showConfirmDialog(parent, "Bạn Có Muốn Cập Nhập Không?",
                        "Hỏi") == JOptionPane.NO_OPTION);
                return;
            }else{
                if (dao.update(bd)) {
                    MessageDialogHelper.showMessageDialog(parent, "Bảng Điểm Đã Được Lưu", "Thông Báo");
                }else{
                    MessageDialogHelper.showErrorDialog(parent, "Bảng Điểm Không Lưu Được", "Thông Báo");
                }
            }
            LichSuDiem(txtStudentID.getText(), "Cập nhập");
            LoadDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parent, e.toString(), "Lỗi");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if(txtStudentID.getText().equals("")){
                MessageDialogHelper.showMessageDialog(parent, "Mã Sinh Viên Cần Phải Nhâp", "Lỗi");
                return;
            }
            BangDiemDao dao = new BangDiemDao();
            BangDiem bd = dao.findByMaSinhVien(txtStudentID.getText());
            
            if (bd == null) {
                MessageDialogHelper.showMessageDialog(parent, "Mã Sinh Không Có Tồn Tại Trong Danh Sách", "Lỗi");
                return;
            } 
            if (MessageDialogHelper.showConfirmDialog(parent, "Bạn Có Muốn Xóa Điểm Của Sinh Viên Không"
                    , "Hỏi") == JOptionPane.NO_OPTION) {
                return;
            }
            if(dao.deleteByMaSinhVien(txtStudentID.getText())){
                MessageDialogHelper.showMessageDialog(parent, "Điểm Của Sinh VIên Đã Được Xóa", "Thông báo");
            }else{
                MessageDialogHelper.showMessageDialog(parent, "Điểm Của Sinh Viên Không Xóa Được", "Thông Báo");
            }
            LichSuDiem(txtStudentID.getText(), "Xóa");
            LoadDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parent, e.toString(), "Lỗi");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblBangDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangDiemMouseClicked
        try {
            int row = tblBangDiem.getSelectedRow();
            txtStudentID.setText(tblBangDiem.getValueAt(row, 0).toString());
            txtJava.setText(tblBangDiem.getValueAt(row, 1).toString());
            txtSql.setText(tblBangDiem.getValueAt(row, 2).toString());
            txtPhanTichHeThong.setText(tblBangDiem.getValueAt(row, 3).toString());
            txtIOS.setText(tblBangDiem.getValueAt(row, 4).toString());
            txtPHP.setText(tblBangDiem.getValueAt(row, 5).toString());
            lblGpa.setText(tblBangDiem.getValueAt(row, 6).toString());
            
            txtStudentIDFocusLost(null);
        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBangDiemMouseClicked

    private void btnTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopActionPerformed
        bangdiemhoi = new BangDiemHoi(parent, true);
        bangdiemhoi.setVisible(true);
        if (bangdiemhoi.LBLTop() == "") {
                return;
        }else{
            int top = Integer.parseInt(bangdiemhoi.LBLTop());

            try {
                BangDiemDao dao = new BangDiemDao();
                List<BangDiem> list = dao.findTop(top);
                tblModel.setRowCount(0);
                for (BangDiem bd : list) {
                    tblModel.addRow(new Object[]{ bd.getMaSinhVien(), bd.getJava(), bd.getSQL(),
                                    bd.getPhanTichHeThong(), bd.getIos(), bd.getPhp(),
                                    (bd.getJava() + bd.getSQL() + bd.getPhanTichHeThong() + bd.getIos() + bd.getPhp())/5});
               }
                tblModel.fireTableDataChanged();
            } catch (Exception e) {
                e.printStackTrace();
                MessageDialogHelper.showErrorDialog(parent, e.getMessage(), "Lỗi");
           }
        }
    }//GEN-LAST:event_btnTopActionPerformed

    private void btnXemTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTatCaActionPerformed
        LoadDataToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemTatCaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTop;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXemTatCa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JTable tblBangDiem;
    private javax.swing.JTextField txtIOS;
    private javax.swing.JTextField txtJava;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPHP;
    private javax.swing.JTextField txtPhanTichHeThong;
    private javax.swing.JTextField txtSql;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentIDSearch;
    // End of variables declaration//GEN-END:variables
}
