/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BangDangNhap;

import Helper.MessageDialogHelper;
import Helper.SharedData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Admin
 */
public class MainForm extends javax.swing.JFrame {
    private StudentManagementPanel mStudentPanel;
    private GPAManagementPanel mGPAPanel;
    private ClassManagementPanel mClassPanel;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);// căng giữ
        
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH); // phóng to kích thước
        
        
//        LoginDialog dialog = new LoginDialog(this, true);
//        dialog.setVisible(true);//Gọi này để hiện thị LoginDialog
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);//Gọi này để hiện thị LoginDialog
        processLoginSuccessful();
        Dong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblLoginName = new javax.swing.JLabel();
        lblRode = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnStudentManagerment = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnGPAManagemenet = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnClass = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tbrAboutUs = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        tbrLogout = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        tplMainBoard = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        hethong = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuFile_Exit = new javax.swing.JMenuItem();
        QuanLy = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuManageStudent = new javax.swing.JMenuItem();
        mnuManageGPA = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuAboutUss = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblLoginName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblLoginName, java.awt.BorderLayout.CENTER);

        lblRode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblRode, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, 59));

        jToolBar1.setRollover(true);

        btnStudentManagerment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudentManagerment.setForeground(new java.awt.Color(255, 0, 0));
        btnStudentManagerment.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\10207-man-student-light-skin-tone-icon-24.png")); // NOI18N
        btnStudentManagerment.setText("Quản Lý Sinh Viên");
        btnStudentManagerment.setFocusable(false);
        btnStudentManagerment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStudentManagerment.setSelectedIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\10207-man-student-light-skin-tone-icon-32.png")); // NOI18N
        btnStudentManagerment.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStudentManagerment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagermentActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStudentManagerment);
        jToolBar1.add(jSeparator5);

        btnGPAManagemenet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGPAManagemenet.setForeground(new java.awt.Color(255, 0, 0));
        btnGPAManagemenet.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\gpa-icon-24.png")); // NOI18N
        btnGPAManagemenet.setText("Quản Lý Điểm");
        btnGPAManagemenet.setFocusable(false);
        btnGPAManagemenet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGPAManagemenet.setSelectedIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\gpa-icon-32.png")); // NOI18N
        btnGPAManagemenet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGPAManagemenet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPAManagemenetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGPAManagemenet);
        jToolBar1.add(jSeparator6);

        btnClass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClass.setForeground(new java.awt.Color(255, 0, 0));
        btnClass.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Science-Classroom-icon-24.png")); // NOI18N
        btnClass.setText("Quản Lý Lớp");
        btnClass.setAutoscrolls(true);
        btnClass.setFocusable(false);
        btnClass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClass.setSelectedIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Science-Classroom-icon-32.png")); // NOI18N
        btnClass.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClass);
        jToolBar1.add(jSeparator7);

        tbrAboutUs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbrAboutUs.setForeground(new java.awt.Color(255, 0, 0));
        tbrAboutUs.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-help-about-icon-24.png")); // NOI18N
        tbrAboutUs.setText("Giới Thiệu");
        tbrAboutUs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAboutUs.setSelectedIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-help-about-icon-32.png")); // NOI18N
        tbrAboutUs.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutUsActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAboutUs);
        jToolBar1.add(jSeparator4);

        tbrLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbrLogout.setForeground(new java.awt.Color(255, 0, 0));
        tbrLogout.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\logout-icon-24.png")); // NOI18N
        tbrLogout.setText("Đăng Xuất");
        tbrLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrLogout.setSelectedIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\logout-icon-32.png")); // NOI18N
        tbrLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrLogout);
        jToolBar1.add(jSeparator8);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, -1, 70));

        tplMainBoard.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tplMainBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(tplMainBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1380, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\backgroup6.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        hethong.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\User.png")); // NOI18N
        hethong.setText("Hệ Thống");
        hethong.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\logout-icon-16.png")); // NOI18N
        jMenuItem2.setText("Đăng xuất");
        hethong.add(jMenuItem2);

        menuFile_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuFile_Exit.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Button-Close-icon-16.png")); // NOI18N
        menuFile_Exit.setText("Thoát");
        menuFile_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFile_ExitActionPerformed(evt);
            }
        });
        hethong.add(menuFile_Exit);

        jMenuBar1.add(hethong);

        QuanLy.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Users.png")); // NOI18N
        QuanLy.setText("Quản Lý");
        QuanLy.add(jSeparator2);

        menuManageStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuManageStudent.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\10207-man-student-light-skin-tone-icon-16.png")); // NOI18N
        menuManageStudent.setText("Quản Lý Sinh Viên");
        menuManageStudent.setInheritsPopupMenu(true);
        menuManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageStudentActionPerformed(evt);
            }
        });
        QuanLy.add(menuManageStudent);

        mnuManageGPA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuManageGPA.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\gpa-icon.png")); // NOI18N
        mnuManageGPA.setText("Quản Lý Điểm");
        mnuManageGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageGPAActionPerformed(evt);
            }
        });
        QuanLy.add(mnuManageGPA);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Science-Classroom-icon-16.png")); // NOI18N
        jMenuItem1.setText("Quản Lý Lớp");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        QuanLy.add(jMenuItem1);

        jMenuBar1.add(QuanLy);

        jMenu1.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Notes.png")); // NOI18N
        jMenu1.setText("Lịch Sử");
        jMenu1.add(jSeparator9);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Lịch Sử Sinh Viên");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Lịch Sử Điểm");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem8.setText("Lịch Sử Lớp");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Help-icon-16.png")); // NOI18N
        jMenu3.setText("Trợ Giúp");
        jMenu3.add(jSeparator3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-help-about-icon-16.png")); // NOI18N
        jMenuItem5.setText("Nội Dung");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        mnuAboutUss.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuAboutUss.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Help-icon-16.png")); // NOI18N
        mnuAboutUss.setText("Giới Thiệu");
        mnuAboutUss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutUssActionPerformed(evt);
            }
        });
        jMenu3.add(mnuAboutUss);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void menuFile_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFile_ExitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFile_ExitActionPerformed

    private void menuManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageStudentActionPerformed
        mStudentPanel = new StudentManagementPanel();
        ImageIcon icon = new ImageIcon("S:/Java/BangDiem/AppSV/src/BangDangNhap/Icon/10207-man-student-light-skin-tone-icon-16.png");
        tplMainBoard.addTab("Quản lý sinh viên", icon,mStudentPanel,"Quản lý sinh viên"); 
        // TODO add your handling code here:
    }//GEN-LAST:event_menuManageStudentActionPerformed

    private void mnuManageGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageGPAActionPerformed
            mGPAPanel = new GPAManagementPanel();
            ImageIcon icon = new ImageIcon("S:/Java/BangDiem/AppSV/src/BangDangNhap/Icon/gpa-icon.png");
            tplMainBoard.addTab("Quản lý điểm", icon, mGPAPanel, "Quản lý điểm");  
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuManageGPAActionPerformed

    private void tbrAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutUsActionPerformed
        AboutUsDialog aboutDialog = new AboutUsDialog(this, true);       
        aboutDialog.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tbrAboutUsActionPerformed
  
    private void mnuAboutUssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutUssActionPerformed
        tbrAboutUsActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuAboutUssActionPerformed

    private void tbrLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrLogoutActionPerformed
        tplMainBoard.removeAll();
        if(MessageDialogHelper.showConfirmDialog(this, "Bạn Có muốn Thoát Không",
                "Hỏi") == JOptionPane.NO_OPTION){
            return;
        }
        
        LoginDialog loginDialog = new LoginDialog(this, true);       
        loginDialog.setVisible(true);
        processLoginSuccessful();
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tbrLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        LoginDialog dialog = new LoginDialog(this, true);
//        dialog.setVisible(true);//Gọi này để hiện thị LoginDialog
//        processLoginSuccessful();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    private void processLoginSuccessful(){
        lblLoginName.setText(SharedData.nguoiDangNhap.getTenDangNhap());
        lblRode.setText(SharedData.nguoiDangNhap.getVaiTro());
       
    }
    
    private void btnClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassActionPerformed
        
            mClassPanel = new ClassManagementPanel();
            ImageIcon icon = new ImageIcon("S:/Java/BangDiem/AppSV/src/BangDangNhap/Icon/Science-Classroom-icon-16.png");
            tplMainBoard.addTab("Quản lý sinh viên", icon,mClassPanel,"Quản lý lớp"); 
                
// TODO add your handling code here:
    }//GEN-LAST:event_btnClassActionPerformed

    private void btnGPAManagemenetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPAManagemenetActionPerformed
        mnuManageGPAActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGPAManagemenetActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        HelperDialog helperDL = new HelperDialog(this, true);
        helperDL.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        btnClassActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnStudentManagermentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagermentActionPerformed
        menuManageStudentActionPerformed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentManagermentActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        LichSuSinhVien LS_SV = new LichSuSinhVien(this, true);
        LS_SV.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        LichSuDiem LS_Diem = new LichSuDiem(this, true);
        LS_Diem.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        LichSuLop LS_Class = new LichSuLop(this, true);
        LS_Class.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu QuanLy;
    private javax.swing.JButton btnClass;
    private javax.swing.JButton btnGPAManagemenet;
    private javax.swing.JButton btnStudentManagerment;
    private javax.swing.JMenu hethong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLoginName;
    private javax.swing.JLabel lblRode;
    private javax.swing.JMenuItem menuFile_Exit;
    private javax.swing.JMenuItem menuManageStudent;
    private javax.swing.JMenuItem mnuAboutUss;
    private javax.swing.JMenuItem mnuManageGPA;
    private javax.swing.JButton tbrAboutUs;
    private javax.swing.JButton tbrLogout;
    private javax.swing.JTabbedPane tplMainBoard;
    // End of variables declaration//GEN-END:variables
    public void Dong(){
        tplMainBoard.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {}

            @Override
            public void mousePressed(MouseEvent e) {
                int index = tplMainBoard.getSelectedIndex();
                JPopupMenu popupMenu = new JPopupMenu();
                JMenuItem delete = new JMenuItem("Đóng");
                delete.addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        tplMainBoard.remove(index);
                    }
                    
                });
                popupMenu.add(delete);
                popupMenu.show(tplMainBoard, e.getX(), e.getY()-40);
            }

            @Override
            public void mouseReleased(MouseEvent e) { }

            @Override
            public void mouseEntered(MouseEvent e) {}

            @Override
            public void mouseExited(MouseEvent e) {}
        });
    }
}
