/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BangDangNhap;


import Dao.LichSuDao;
import Dao.SinhVienDao;
import Helper.DataValidator;
import Helper.ImageHelper;
import Helper.MessageDialogHelper;
import Helper.SharedData;
import java.awt.Image;
import java.io.File;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import model.LichSu;
import model.SinhVien;

/**
 *
 * @author Admin
 */
public class StudentManagementPanel extends javax.swing.JPanel {
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    private byte[] personalImage;
    /**
     * Creates new form StudentManagementPanel
     */
    public StudentManagementPanel() {
        initComponents();
        
        
        initTable();
        LoadDataToTable();
        
    }
    private void initTable(){
        Object[] columns = {"Mã Sinh Viên","Họ Tên","Ngày Sinh","Email","SĐT","Giới Tính","Địa Chỉ","Tình Trạng"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columns);
        tblStudent.setModel(tblModel);
    }
    private void LoadDataToTable(){
        try {
            SinhVienDao dao = new SinhVienDao();
            List<SinhVien> list = dao.findAll();
            tblModel.setRowCount(0);
            for (SinhVien sv : list) {
                tblModel.addRow(new Object[]{sv.getMaSinhVien(),sv.getHoTen(),sv.getNgaySinh(),sv.getEmail(),
                sv.getSoDT(), sv.getGioiTinh()== 0 ? "Nam":"Nữ", sv.getDiaChi(), sv.getTinhTrang()== 0 ? "Nghỉ Học":"Đang Học"});
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGT = new javax.swing.ButtonGroup();
        jLocaleChooserBeanInfo1 = new com.toedter.components.JLocaleChooserBeanInfo();
        jDateChooserBeanInfo1 = new com.toedter.calendar.JDateChooserBeanInfo();
        arrayListModel1 = new com.jgoodies.common.collect.ArrayListModel();
        linkedListModel1 = new com.jgoodies.common.collect.LinkedListModel();
        linkedListModel2 = new com.jgoodies.common.collect.LinkedListModel();
        buttonGroupTT = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnBrowse1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdoFemale = new javax.swing.JRadioButton();
        txtStudentID = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();
        txtPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ckbDangHoc = new javax.swing.JCheckBox();
        ckbNghiHoc = new javax.swing.JCheckBox();
        btnAll = new javax.swing.JButton();
        btnSearchDangHoc = new javax.swing.JButton();
        btnSearchNghiHoc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();

        btnDelete.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-edit-delete-icon-16.png")); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\login1.png")); // NOI18N

        btnBrowse.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\open-file-icon-16.png")); // NOI18N
        btnBrowse.setText("Mở Hình");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnBrowse1.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Button-delete-icon.png")); // NOI18N
        btnBrowse1.setText("Xóa Hình");
        btnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowse1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse)
                    .addComponent(btnBrowse1))
                .addContainerGap())
        );

        jLabel2.setText("Mã sinh viên:");

        jLabel3.setText("Họ và tên:");

        jLabel4.setText("Email:");

        txaAddress.setColumns(20);
        txaAddress.setRows(5);
        jScrollPane1.setViewportView(txaAddress);

        jLabel6.setText("Giới tính:");

        buttonGroupGT.add(rdoMale);
        rdoMale.setText("Nam");

        jLabel7.setText("Địa chỉ:");

        buttonGroupGT.add(rdoFemale);
        rdoFemale.setText("Nữ");

        btnNew.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\new-icon-16.png")); // NOI18N
        btnNew.setText("Tạo Mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Save-icon.png")); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("S:\\Java\\BangDiem\\AppSV\\src\\BangDangNhap\\Icon\\Actions-document-edit-icon-16.png")); // NOI18N
        btnUpdate.setText("Cập Nhập");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý Sinh Viên");

        jLabel9.setText("Ngày sinh:");

        date_chooser.setDateFormatString("dd-MM-yyyy");

        jLabel10.setText("Số điện thoại:");

        jLabel8.setText("Tình trạng:");

        buttonGroupTT.add(ckbDangHoc);
        ckbDangHoc.setText("Đang Học");

        buttonGroupTT.add(ckbNghiHoc);
        ckbNghiHoc.setText("Nghỉ Học");

        btnAll.setText("Hiện Tất Cả Học Sinh");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        btnSearchDangHoc.setText("Hiện Các Học Sinh Đang Học");
        btnSearchDangHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDangHocActionPerformed(evt);
            }
        });

        btnSearchNghiHoc.setText("Hiện Các Học Sinh Nghỉ Học");
        btnSearchNghiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNghiHocActionPerformed(evt);
            }
        });

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblStudent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel10))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(rdoMale)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(rdoFemale))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addComponent(ckbDangHoc)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(ckbNghiHoc))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(btnUpdate)
                                                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(0, 773, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSearchNghiHoc)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearchDangHoc)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAll)
                                        .addGap(17, 17, 17))))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoMale)
                            .addComponent(rdoFemale)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(ckbDangHoc)
                                    .addComponent(ckbNghiHoc)
                                    .addComponent(btnSearchNghiHoc)
                                    .addComponent(btnSearchDangHoc)
                                    .addComponent(btnAll)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNew)
                            .addComponent(btnSave))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtStudentID.setText("");
        txtName.setText("");
        date_chooser.setDate(null);
        txtEmail.setText("");
        txtPhone.setText("");
        txaAddress.setText("");
        buttonGroupGT.clearSelection();
        buttonGroupTT.clearSelection();
        personalImage = null;
        ImageIcon icon = new ImageIcon("S:/Java/BangDiem/AppSV/src/BangDangNhap/Icon/login1.png");
        lblImage.setIcon(icon);
        
        txtStudentID.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewActionPerformed
    private void LichSuSinhVien(String MaSV, String GhiChu){   
        try {
            LichSu LS = new LichSu();
            LS.setMaSV(MaSV); 
            LS.setGhiChu(GhiChu);

            LichSuDao dao = new LichSuDao();
            dao.insert_SV(LS);

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, "Sinh Viên Đã Có Trong Danh Sách","Lỗi" );
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Mã Sinh Viên Không Được Để Trống");
        DataValidator.validateEmpty(txtName, sb, "Tên Sinh Viên Không Được Để Trống");
        if (sb.length() >0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
        }
        try {
            SinhVien sv = new SinhVien();
            sv.setMaSinhVien(txtStudentID.getText());
            sv.setHoTen(txtName.getText());
            sv.setEmail(txtEmail.getText());
            sv.setSoDT(txtPhone.getText());
            sv.setDiaChi(txaAddress.getText());
            sv.setGioiTinh(rdoFemale.isSelected() ? 1:0);
            sv.setHinh(personalImage);
            
//            String date = ((JTextField)date_chooser.getDateEditor().getUiComponent()).getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(date_chooser.getDate());
            sv.setNgaySinh(date);
            
            sv.setTinhTrang(ckbDangHoc.isSelected() ? 1:0);
   
            SinhVienDao dao = new SinhVienDao();
            if (dao.insert(sv)) { // Kiểm tra chèn cho sinh viên 
                MessageDialogHelper.showMessageDialog(parentForm, "Sinh Viên Đã Được Lưu", "Thông báo");                
                LoadDataToTable();
            }else{
                MessageDialogHelper.showConfirmDialog(parentForm, "Sinh Viên Không Được Lưu", "Cảnh Báo");
            }
            LichSuSinhVien(txtStudentID.getText(), "Lưu");
            LoadDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, "Sinh Viên Đã Có Trong Danh Sách","Lỗi" );
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Mã Sinh Viên Trống Hoặc Sai Mã Sinh Viên ");
        if (sb.length() >0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
        }
        
        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn muốn cập nhập sinh viên không",
                "Hỏi") == JOptionPane.NO_OPTION ) {
            return;          
        }       
        try {
            SinhVien sv = new SinhVien();
            sv.setMaSinhVien(txtStudentID.getText());
            sv.setHoTen(txtName.getText());
            sv.setEmail(txtEmail.getText());
            sv.setSoDT(txtPhone.getText());
            sv.setDiaChi(txaAddress.getText());
            sv.setGioiTinh(rdoFemale.isSelected() ? 1:0);
            sv.setHinh(personalImage);
            
//            String date = ((JTextField)date_chooser.getDateEditor().getUiComponent()).getText();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date = dateFormat.format(date_chooser.getDate());
            sv.setNgaySinh(date);
            
            sv.setTinhTrang(ckbDangHoc.isSelected() ? 1:0);
   
            SinhVienDao dao = new SinhVienDao();
            if (dao.update(sv)) { // Kiểm tra chèn cho sinh viên 
                MessageDialogHelper.showMessageDialog(parentForm, "Sinh Viên Đã Được Cập Nhập", "Thông báo");
                LoadDataToTable();
            }else{
                MessageDialogHelper.showConfirmDialog(parentForm, "Sinh Viên Không Được Cập Nhập", "Cảnh Báo");
            }       
            LichSuSinhVien(txtStudentID.getText(), "Cập nhập");
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(),"Lỗi" );
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtStudentID, sb, "Mã Sinh Viên Trống Hoặc Sai Mã Sinh Viên ");
        if (sb.length() >0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
        }
        
        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn muốn xóa sinh viên không",
                "Hỏi") == JOptionPane.NO_OPTION ) {
            return;          
        }
        
        try {
            SinhVienDao dao = new SinhVienDao();
            if (dao.delete(txtStudentID.getText())) { // Kiểm tra chèn cho sinh viên 
                LichSuSinhVien(txtStudentID.getText(), "Xóa");
                MessageDialogHelper.showMessageDialog(parentForm, "Sinh Viên Đã Được Xóa", "Thông báo");
                btnNewActionPerformed(evt);           
//                LichSuSinhVien(txtStudentID.getText(), "Xóa");
                LoadDataToTable();
            }else{
                MessageDialogHelper.showConfirmDialog(parentForm, "Sinh Viên Không Được Xóa", "Cảnh Báo");
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(),"Lỗi" );
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".png");
                }
            }

            @Override
            public String getDescription() {
                 return "Image File (*.png)";
            }
        });
        if (chooser.showOpenDialog(parentForm) == JFileChooser.CANCEL_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        try {
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 180, 150);
            ImageIcon resizedIcon = new ImageIcon(img);
            lblImage.setIcon(resizedIcon);
            personalImage = ImageHelper.topByteArray(img, "png");
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showMessageDialog(parentForm, e.getMessage(), "Lỗi");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSearchDangHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDangHocActionPerformed
        try {
            SinhVienDao dao = new SinhVienDao();
            List<SinhVien> list = dao.find_TinhTrang("1");
            tblModel.setRowCount(0);
            for (SinhVien sv : list) {
                tblModel.addRow(new Object[]{sv.getMaSinhVien(),sv.getHoTen(),sv.getNgaySinh(),sv.getEmail(),
                sv.getSoDT(), sv.getGioiTinh()== 0 ? "Nam":"Nữ", sv.getDiaChi(), sv.getTinhTrang()== 0 ? "Nghỉ Học":"Đang Học"});
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnSearchDangHocActionPerformed

    private void btnSearchNghiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNghiHocActionPerformed
        try {
            SinhVienDao dao = new SinhVienDao();
            List<SinhVien> list = dao.find_TinhTrang("0");
            tblModel.setRowCount(0);
            for (SinhVien sv : list) {
                tblModel.addRow(new Object[]{sv.getMaSinhVien(),sv.getHoTen(),sv.getNgaySinh(),sv.getEmail(),
                sv.getSoDT(), sv.getGioiTinh()== 0 ? "Nam":"Nữ", sv.getDiaChi(), sv.getTinhTrang()== 0 ? "Nghỉ Học":"Đang Học"});
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnSearchNghiHocActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        LoadDataToTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse1ActionPerformed
        ImageIcon icon = new ImageIcon("S:/Java/BangDiem/AppSV/src/BangDangNhap/Icon/login1.png");
        lblImage.setIcon(icon);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowse1ActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        try {
            int row = tblStudent.getSelectedRow();
            
            if (row >= 0) {
                String id = (String) tblStudent.getValueAt(row, 0);
                SinhVienDao dao = new SinhVienDao();
                SinhVien sv = dao.findByID(id);
                
                if (sv != null) {
                    txtStudentID.setText(sv.getMaSinhVien());
                    txtName.setText(sv.getHoTen());
                    Date date = Date.valueOf(sv.getNgaySinh());
                    date_chooser.setDate(date);
                    txtEmail.setText(sv.getEmail());
                    txtPhone.setText(sv.getSoDT());
                    txaAddress.setText(sv.getDiaChi());
                    if (sv.getGioiTinh() == 1) {
                        rdoFemale.setSelected(true);
                    }else{
                        rdoMale.setSelected(true);
                    }
                    if (sv.getHinh() != null) {
                        Image img = ImageHelper.createImageFromByteArray(sv.getHinh(), "png");
                        lblImage.setIcon(new ImageIcon(img));
                        personalImage = sv.getHinh();
                    }else{
                        personalImage = sv.getHinh();
                        ImageIcon icon = new ImageIcon("S:/Java/BangDiem/AppSV/src/BangDangNhap/Icon/login1.png");
                        lblImage.setIcon(icon);
                    }
                    if (sv.getTinhTrang() == 1) {
                        ckbDangHoc.setSelected(true);
                    } else {
                        ckbNghiHoc.setSelected(true);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.toString(), "Lỗi");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_tblStudentMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jgoodies.common.collect.ArrayListModel arrayListModel1;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnBrowse1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchDangHoc;
    private javax.swing.JButton btnSearchNghiHoc;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroupGT;
    private javax.swing.ButtonGroup buttonGroupTT;
    private javax.swing.JCheckBox ckbDangHoc;
    private javax.swing.JCheckBox ckbNghiHoc;
    private com.toedter.calendar.JDateChooser date_chooser;
    private com.toedter.calendar.JDateChooserBeanInfo jDateChooserBeanInfo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooserBeanInfo jLocaleChooserBeanInfo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImage;
    private com.jgoodies.common.collect.LinkedListModel linkedListModel1;
    private com.jgoodies.common.collect.LinkedListModel linkedListModel2;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextArea txaAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
    
}
