/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TableRow;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author SonHeo
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public Table() {
        this.setLocationRelativeTo(null);
        initComponents();
        LoadDataJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        bttNew = new javax.swing.JButton();
        bttSave = new javax.swing.JButton();
        bttUpdate = new javax.swing.JButton();
        bttDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblyou = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Email:");

        jLabel3.setText("Pass:");

        jLabel4.setText("Country:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quan Ly Nhan Vien");

        bttNew.setText("New");
        bttNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttNewActionPerformed(evt);
            }
        });

        bttSave.setText("Save");
        bttSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSaveActionPerformed(evt);
            }
        });

        bttUpdate.setText("Update");
        bttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttUpdateActionPerformed(evt);
            }
        });

        bttDelete.setText("Delete");
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        tblyou.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblyou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblyouMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblyou);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(txtName)
                            .addComponent(txtPass)
                            .addComponent(txtEmail)
                            .addComponent(txtCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttNew))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttSave))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblyouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblyouMouseClicked
        int rows = tblyou.getSelectedRow();
        txtName.setText(tblyou.getValueAt(rows, 0).toString());
        txtEmail.setText(tblyou.getValueAt(rows, 1).toString());
        txtPass.setText(tblyou.getValueAt(rows, 2).toString());
        txtCountry.setText(tblyou.getValueAt(rows, 3).toString());
        
    }//GEN-LAST:event_tblyouMouseClicked

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        try {
            Connection conn = KetNoi();
            
            Statement sttm = conn.createStatement();
            String sql = "Delete from you where uname=?";
            
            PreparedStatement delete = conn.prepareStatement(sql);
            delete.setString(1, txtName.getText());
            delete.executeUpdate();
            conn.close();
            LoadDataJTable();
        } catch (Exception e) {
            System.err.println("No");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bttDeleteActionPerformed

    private void bttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttUpdateActionPerformed
        StringBuilder sb = new StringBuilder();
        int index = tblyou.getSelectedRow();
        if(txtName.getText()!= (String)tblyou.getValueAt(index,0)) {
            sb.append("khong co name\n");
        } 
        
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Erro", 0);
        } else { 
        try {
                Connection conn = KetNoi();
                String sql = "Update you set  umail=?, upass=?, ucountry=? where uname=?";
                
                PreparedStatement update = conn.prepareStatement(sql);
                update.setString(1, txtEmail.getText());
                update.setString(2, txtPass.getText());
                update.setString(3, txtCountry.getText());
                update.setString(4, txtName.getText());
                update.executeUpdate();
                conn.close();
                LoadDataJTable();
                
            } catch (Exception e) {
                System.err.println("No");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bttUpdateActionPerformed

    private void bttSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSaveActionPerformed
        
        try {
            Connection conn = KetNoi();
            
            String sql = "Insert into you values(?,?,?,?)";
            PreparedStatement save = conn.prepareStatement(sql);
            save.setString(1, txtName.getText());
            save.setString(2, txtEmail.getText());
            save.setString(3, txtPass.getText());
            save.setString(4, txtCountry.getText());
            save.executeUpdate();
            conn.close();
            LoadDataJTable();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Da trung uname");
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_bttSaveActionPerformed

    private Connection KetNoi() throws SQLException, ClassNotFoundException {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost:1433;databaseName=demo;";
        Connection conn = DriverManager.getConnection(url, "sa", "reallyStrongPwd123");
        return conn;
    }

    private void bttNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttNewActionPerformed
        txtName.setText("");
        txtEmail.setText("");
        txtPass.setText("");
        txtCountry.setText("");
        txtName.requestFocus(); //hien dau gach
        // TODO add your handling code here:
    }//GEN-LAST:event_bttNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttNew;
    private javax.swing.JButton bttSave;
    private javax.swing.JButton bttUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblyou;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables

    private void LoadDataJTable() {
        try {
            Connection conn = KetNoi();
            
            Statement sttm = conn.createStatement();
            String sql = "Select * from you";
            ResultSet rs = sttm.executeQuery(sql);
            
            if (conn != null) {
                System.err.println("Thanh cong");
                
                Object[] columns = {"Uname", "Umail", "Upass", "Ucountry"};
                DefaultTableModel model = (DefaultTableModel) tblyou.getModel();
                model.setColumnIdentifiers(columns);
                model.setRowCount(0);
                while (rs.next()) {
                    String uname = rs.getString("uname");
                    String umail = rs.getString("umail");
                    String upass = rs.getString("upass");
                    String ucountry = rs.getString("ucountry");
                    
                    model.addRow(new Object[]{uname, umail, upass, ucountry});
                }
                
            } else {
                System.err.println("No");
            }
        } catch (Exception e) {
            
        }
        //To change body of generated methods, choose Tools | Templates.
    }
}
